src/Entity/RecipeLink.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 */
class RecipeLink
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     * @Assert\Url()
     */
    private $url;

    /**
     * @var Recipe
     *
     * @ORM\ManyToOne(targetEntity="Recipe", inversedBy="recipeLinks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipe;


    public function __toString()
    {
        return $this->getUrl();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * @param string $url
     * @return RecipeLink
     */
    public function setUrl(?string $url): RecipeLink
    {
        $this->url = $url;
        return $this;
    }

    /**
     * @return Recipe
     */
    public function getRecipe(): Recipe
    {
        return $this->recipe;
    }

    /**
     * @return Recipe
     */
    public function setRecipe(?Recipe $recipe): RecipeLink
    {
        $this->recipe = $recipe;
        return $this;
    }

    /**
     * @return string
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * @param string $text
     * @return RecipeLink
     */
    public function setText(?string $text): RecipeLink
    {
        $this->text = $text;
        return $this;
    }


    public function getLinkText()
    {
        if ($this->text == '') {
            return $this->getUrl();
        }
        return $this->text;
    }

}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\ImageFile;
use App\Entity\Recipe;
use App\Entity\RecipeTag;
use App\Events;
use App\Form\CommentType;
use App\Form\RecipeDisplaySettingsType;
use App\Form\RecipeFilterType;
use App\Form\RecipeImportFromLinkType;
use App\Form\RecipeType;
use App\Form\Type\IngredientType;
use App\Repository\RecipeRepository;
use App\Service\DatabaseTranslationLoaderService;
use App\Service\IngredientService;
use App\Service\PDFExportService;
use App\Service\RecipeListService;
use App\Service\RecipeRatingService;
use App\Service\RecipeService;
use App\Service\RecipeTagService;
use App\Service\RecipeUserService;
use App\Utils\Slugger;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\Translator;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Controller used to manage blog contents in the public part of the site.
 *
 * @Route("/recipes")
 *
 * @author Ryan Weaver <weaverryan@gmail.com>
 * @author Javier Eguiluz <javier.eguiluz@gmail.com>
 */
class RecipesController extends AbstractController
{

    const PARAMETER_FROM_LINK = 'from_link';

    const FORM_RECIPE_ID = 'recipe';
    const FORM_RECIPE_LANGUAGE = 'language';

    /**
     * Recipes overview.
     *
     * @Route("/", name="recipes_overview")
     * @Security("is_granted('ROLE_USER')")
     * @Method("GET")
     */
    public function myOverviewAction(RecipeListService $recipeListService): Response
    {

        $authorRecipeLists = $recipeListService->getAllForUser($this->getUser());

        return $this->render(
            'front/recipes/overview.html.twig',
            [
                'recipeLists' => $authorRecipeLists,
                'user' => $this->getUser(),
            ]
        );
    }

    /**
     * Lists all Recipe entities.
     *
     * @Route("/my_recipes", name="recipes_list_my")
     * @Security("is_granted('ROLE_USER')")
     * @Method("GET")
     */
    public function listMyAction(Request $request, RecipeRepository $recipes, TranslatorInterface $translator): Response
    {
        $onlyWithoutRecipeList = boolval($request->query->get('only_without_recipe_list'));
        $authorRecipes = $recipes->getMyRecipes($this->getUser(), $onlyWithoutRecipeList);
        $title = $onlyWithoutRecipeList ? $translator->trans('title.all_recipes_without_list') : $translator->trans('title.all_recipes');

        return $this->render(
            'front/recipes/list.html.twig',
            [
                'recipes' => $authorRecipes,
                'user' => $this->getUser(),
                'site_title' => $title,
            ]
        );
    }

    /**
     * Displays a form to edit an existing Recipe entity.
     *
     * @Route("/{id}/edit", requirements={"id": "\d+"}, name="recipes_edit")
     * @Security("is_granted('show', recipe)")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request,
                               RecipeService $recipeService,
                               Recipe $recipe,
                               IngredientService $ingredientService,
                               RecipeTagService $recipeTagService,
                               RecipeListService $recipeListService
    ): Response {
        $this->denyAccessUnlessGranted('edit', $recipe, 'Recipes can only be edited by their authors.');

        $form = $this->createForm(RecipeType::class, $recipe, ['user' => $this->getUser(), 'recipe' => $recipe]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipeService->saveRecipe($recipe);
            $this->addFlash('success', 'messages.recipe_modified');

            return $this->redirectToRoute('recipes_edit', ['id' => $recipe->getId()]);
        }

        if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', 'messages.recipe_faulty');
        }

        return $this->render('front/recipes/edit.html.twig', [
            'recipe' => $recipe,
            'ingredientList' => $ingredientService->getAllNames(),
            'form' => $form->createView(),
            'recipeTags' => $recipeTagService->getAllNames(),
            'recipeLists' => $recipeListService->getAllForUser($this->getUser(), true),
        ]);
    }

    /**
     * Add a recipe to collected recipes to use them in lists etc.
     *
     * @Route("/{id}/add_to_collection", requirements={"id": "\d+"}, name="recipes_add_to_collection")
     * @Security("is_granted('show', recipe)")
     * @Method({"GET", "POST"})
     */
    public function addToCollectionAction(Request $request,
                                          RecipeService $recipeService,
                                          Recipe $recipe
    ): Response {

        if ($recipeService->addRecipeToUserCollection($recipe, $this->getUser())) {
            $this->addFlash('success', 'messages.recipe_added_to_collection');
        }

        return $this->redirectToRoute('recipes_show', ['slug' => $recipe->getSlug()]);
    }

    /**
     * Remove a recipe from collected recipes
     *
     * @Route("/{id}/remove_from_collection", requirements={"id": "\d+"}, name="recipes_remove_from_collection")
     * @Security("is_granted('show', recipe)")
     * @Method({"GET", "POST"})
     */
    public function removeFromCollectionAction(Request $request,
                                          RecipeService $recipeService,
                                          Recipe $recipe
    ): Response {

        if ($recipeService->removeRecipeFromUserCollection($recipe, $this->getUser())) {
            $this->addFlash('success', 'messages.recipe_removed_from_collection');
        }

        return $this->redirectToRoute('recipes_show', ['slug' => $recipe->getSlug()]);
    }

    /**
     * Creates a new Recipe entity.
     *
     * @Route("/new", name="recipes_new", defaults={"quick": false})
     * @Route("/new_quick", name="recipes_new_quick", defaults={"quick": true})
     * @Method({"GET", "POST"})
     *
     * NOTE: the Method annotation is optional, but it's a recommended practice
     * to constraint the HTTP methods each controller responds to (by default
     * it responds to all methods).
     * @param Request $request
     * @param RecipeService $recipeService
     * @param IngredientService $ingredientService
     * @param RecipeTagService $recipeTagService
     * @param bool $quick
     * @return Response
     */
    public function newAction(Request $request, RecipeService $recipeService, IngredientService $ingredientService, RecipeTagService $recipeTagService, $quick = false): Response
    {
        $recipe = null;
        if (!$request->request->get(self::FORM_RECIPE_ID)) {
            if ($request->query->get(self::PARAMETER_FROM_LINK) !== null) {
                $recipe = $recipeService->createRecipeFromLink($request->get(self::PARAMETER_FROM_LINK), $this->getUser());

                if ($recipe !== null) {
                    $this->addFlash('success', 'messages.recipe_url_parsed');
                } else {
                    $this->addFlash('success', 'messages.recipe_url_parsing_error');
                }
            }
        }

        if (!$recipe) {
            $recipe = new Recipe();
            $recipe->setAuthor($this->getUser());
            if ($quick) {
                $recipe->addImage(new ImageFile());
            }
            $recipe->setLanguage($request->request->get(self::FORM_RECIPE_ID)[self::FORM_RECIPE_LANGUAGE]);
        }

        // See https://symfony.com/doc/current/book/forms.html#submitting-forms-with-multiple-buttons
        $form = $this->createForm(RecipeType::class, $recipe, ['user' => $this->getUser(), 'recipe' => $recipe])
            ->add('saveAndCreateNew', SubmitType::class);

        $form->handleRequest($request);

        // the isSubmitted() method is completely optional because the other
        // isValid() method already checks whether the form is submitted.
        // However, we explicitly add it to improve code readability.
        // See https://symfony.com/doc/current/best_practices/forms.html#handling-form-submits
        if ($form->isSubmitted() && $form->isValid()) {
            $recipeService->saveRecipe($recipe);

            // Flash messages are used to notify the user about the result of the
            // actions. They are deleted automatically from the session as soon
            // as they are accessed.
            // See https://symfony.com/doc/current/book/controller.html#flash-messages
            $this->addFlash('success', 'messages.recipe_created');

            if ($form->get('saveAndCreateNew')->isClicked()) {
                if ($quick) {
                    return $this->redirectToRoute('recipes_new_quick');
                } else {
                    return $this->redirectToRoute('recipes_new');
                }
            }

            return $this->redirectToRoute('recipes_edit', ['id' => $recipe->getId()]);
        }


        if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('danger', 'messages.recipe_faulty');
        }

        return $this->render('front/recipes/new.html.twig', [
            'ingredientList' => $ingredientService->getAllNames(),
            'recipe' => $recipe,
            'form' => $form->createView(),

templates/front/recipes/_form.html.twig
{#
    By default, forms enable client-side validation. This means that you can't
    test the server-side validation errors from the browser. To temporarily
    disable this validation, add the 'novalidate' attribute:

    {{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
#}

{% if show_confirmation|default(false) %}
    {% set attr = {'data-confirmation': 'true'} %}
    {{ include('front/recipes/_delete_recipe_confirmation.html.twig') }}
{% endif %}

{{ form_start(form, {'attr': {'id': 'recipe_form'}}) }}
    {{ include('front/recipes/_form_rows.html.twig', {
        form: form,
        ingredientList: ingredientList,
        recipeTags: recipeTags,
        recipeLists: recipeLists
    }, with_context = false) }}

    <button type="submit" class="{{ button_css|default("btn btn-primary") }}">
        <i class="fa fa-save" aria-hidden="true"></i> {{ button_label|default('label.create_recipe'|trans) }}
    </button>

    {% if include_back_to_home_link|default(false) %}
        <a href="{{ path('recipes_list_my') }}" class="btn btn-link">
            <i class="fa fa-list-alt" aria-hidden="true"></i> {{ 'action.back_to_list'|trans }}
        </a>
    {% endif %}
{{ form_end(form) }}

templates/front/recipes/_form_rows.html.twig
{% import 'front/common/arrayCollection.html.twig' as arrayCollection %}

{{ form_errors(form) }}
{{ form_row(form.title) }}


{{ arrayCollection.start('images', 'title.images', [
    {class: 'col-md-8', field: form.images.vars.prototype.imageFile},
    {class: 'col-md-3', field: form.images.vars.prototype.altText},
    {class: '', field: form.images.vars.prototype.uniqueId},
]) }}

{% for image in form.images %}
    {{ arrayCollection.line([
        {class: 'col-md-8', field: image.imageFile},
        {class: 'col-md-3', field: image.altText},
        {class: '', field: image.uniqueId},
    ]) }}
{% endfor %}

{{ arrayCollection.end(form.images) }}

{{ form_row(form.summary) }}
{{ form_row(form.portions) }}
{{ form_row(form.workingTime) }}
{{ form_row(form.waitingTime) }}
{{ form_row(form.informations) }}

{{ form_row(form.recipeTags, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': form.recipeTags.vars.recipeTags|join('|')}}) }}

{{ form_row(form.authorRecipeLists, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': form.authorRecipeLists.vars.recipeLists|join('|')}}) }}



<div class="row">
    <div class="col-md-12">
        <h3>{{ 'title.ingredients'|trans }}</h3>
        {% set prototype %}
            <div class="row ingredientList">
                <div class="col-md-12">

                    <div class="row">
                        <div class="col-md-6">
                            {{ form_row(form.recipeIngredientLists.vars.prototype.title) }}
                        </div>
                        <div class="col-md-6 deleteButtonContainer">
                        </div>
                    </div>

                    {{ arrayCollection.start('ingredients', 'title.ingredients', [
                        {class: 'col-md-3 stXautoComplete', field: form.recipeIngredientLists.vars.prototype.recipeIngredients.vars.prototype.ingredient, autocomplete: ingredientList  },
                        {class: 'col-md-2 amount', field: form.recipeIngredientLists.vars.prototype.recipeIngredients.vars.prototype.amount},
                        {class: 'col-md-2 unit', field: form.recipeIngredientLists.vars.prototype.recipeIngredients.vars.prototype.unit},
                        {class: 'col-md-4', field: form.recipeIngredientLists.vars.prototype.recipeIngredients.vars.prototype.text},
                    ]) }}

                    {{ arrayCollection.end(form.recipeIngredientLists.vars.prototype.recipeIngredients) }}
                </div>
            </div>
        {% endset %}




        <div class="recipeIngredientLists symfonyArrayCollection" data-add-text="{{ 'action.add_ingredient_list'|trans }}" data-remove-text="{{ 'action.remove_ingredient_list'|trans }}" data-prototype="{{ prototype|e('html_attr') }}">

            {% for currectIngredientList in form.recipeIngredientLists %}

            <div class="row ingredientList">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            {{ form_row(currectIngredientList.title) }}
                        </div>
                        <div class="col-md-6 deleteButtonContainer">
                        </div>
                    </div>

                    {{ arrayCollection.start('ingredients', null, [
                        {class: 'col-md-3 stXautoComplete', field: currectIngredientList.recipeIngredients.vars.prototype.ingredient, autocomplete: ingredientList  },
                        {class: 'col-md-2 amount', field: currectIngredientList.recipeIngredients.vars.prototype.amount},
                        {class: 'col-md-2 unit', field: currectIngredientList.recipeIngredients.vars.prototype.unit},
                        {class: 'col-md-4', field: currectIngredientList.recipeIngredients.vars.prototype.text},
                    ]) }}

                    {% for ingredient in currectIngredientList.recipeIngredients %}
                        {{ arrayCollection.line([
                            {class: 'col-md-3 stXautoComplete', field: ingredient.ingredient, autocomplete: ingredientList},
                            {class: 'col-md-2 amount', field: ingredient.amount},
                            {class: 'col-md-2 unit', field: ingredient.unit},
                            {class: 'col-md-4', field: ingredient.text},
                        ]) }}
                    {% endfor %}

                    {{ arrayCollection.end(currectIngredientList.recipeIngredients) }}
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>



{{ arrayCollection.start('recipeSteps', 'title.steps', [
    {class: 'col-md-9', field: form.recipeSteps.vars.prototype.text},
    {class: 'col-md-3', field: form.recipeSteps.vars.prototype.duration},
]) }}

{% for step in form.recipeSteps %}
    {{ arrayCollection.line([
        {class: 'col-md-9', field: step.text},
        {class: 'col-md-3', field: step.duration},
    ]) }}
{% endfor %}

{{ arrayCollection.end(form.recipeSteps) }}


{{ arrayCollection.start('recipeHints', 'title.hints', [
    {class: 'col-md-11', field: form.recipeHints.vars.prototype.text},
]) }}

{% for hint in form.recipeHints %}
    {{ arrayCollection.line([
        {class: 'col-md-11', field: hint.text},
    ]) }}
{% endfor %}

{{ arrayCollection.end(form.recipeHints) }}


{{ arrayCollection.start('recipeAlternatives', 'title.recipeAlternatives', [
    {class: 'col-md-11', field: form.recipeAlternatives.vars.prototype.text},
]) }}

{% for alternative in form.recipeAlternatives %}
    {{ arrayCollection.line([
        {class: 'col-md-11', field: alternative.text},
    ]) }}
{% endfor %}

{{ arrayCollection.end(form.recipeAlternatives) }}

{{ arrayCollection.start('recipeLinks', 'title.links', [
    {class: 'col-md-5', field: form.recipeLinks.vars.prototype.text},
    {class: 'col-md-6', field: form.recipeLinks.vars.prototype.url},
]) }}

{% for hint in form.recipeLinks %}
    {{ arrayCollection.line([
        {class: 'col-md-5', field: hint.text},
        {class: 'col-md-6', field: hint.url},
    ]) }}
{% endfor %}

{{ arrayCollection.end(form.recipeLinks) }}


{{ form_row(form.private) }}

templates/front/recipes/_recipe.html.twig
<div class="recipe">

    <h1>{{ recipe.title }}</h1>
    <p>&nbsp;</p>

    {% if not app.user or recipe.author.id != app.user.id %}
        <p class="recipe-metadata">
            <span class="metadata"><i class="fa fa-user"></i> {{ recipe.author.fullName }}</span>
            <span class="metadata"><i
                        class="fa fa-calendar"></i> {{ recipe.createdAt|localizeddate('long', 'medium', null, 'UTC') }}</span>
            {% if recipe.ratingGlobal %}
                <span class="metadata">{{ recipe.ratingGlobal|rating(5, "fa-norm", true) }} ({{ recipe.ratingGlobal }})</span>
            {% endif %}
        </p>
    {% endif %}


    {% set images = [] %}
    {% for image in recipe.images %}
        {% set images = images|merge([vich_uploader_asset(image, 'imageFile')]) %}
    {% endfor %}

    {{ bootstrap_carousel(images)|raw }}


    <br>
    {{ recipe.summary|default('')|md2html }}

    <p class="spacer-medium">&nbsp;</p>
    {{ include('front/recipes/_recipe_tags.html.twig') }}

    {% if not shortview|default(false) %}

        <p class="spacer-medium">&nbsp;</p>
        {% if not recipe.recipeLists.empty %}
            <p>{{ 'label.recipeLists'|trans({}, "messages") }}</p>
            <p class="recipe-recipeTags">
                <ul>
                {% for list in recipe.recipeLists %}
                    <li>
                        <a href="{{ path('recipelists_show', {'slug': list.slug}) }}">{{ list.name }}</a>
                    </li>
                {% endfor %}
                </ul>
            </p>
        {% endif %}



        <p>{{ 'label.portions'|trans({}, "messages") }} : {{ recipe.portions }}</p>
        <p>{{ 'label.working_time'|trans({}, "messages") }} : {{ recipe.workingTime|default(' -- ') }}</p>
        <p>{{ 'label.waiting_time'|trans({}, "messages") }} : {{ recipe.waitingTime|default(' -- ') }}</p>
        <p>{{ recipe.informations|purify }}</p>

        <p class="spacer-medium">&nbsp;</p>
        <div class="ingredients">
            <h2>{{ 'title.ingredients'|trans({}, "messages") }}</h2>
            <div>
                {% for ingredientList in recipe.recipeIngredientLists %}
                    <div>
                        {% if ingredientList.title != '' %}
                            <h3>{{ ingredientList.title }}</h3>
                        {% endif %}
                    <ul>
                    {% for ingredient in ingredientList.recipeIngredients %}
                        <li>{{ ingredient|ingredientText(recipe.language) }}</li>
                    {% endfor %}
                    </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
        <p class="spacer-medium">&nbsp;</p>
        <div class="steps">
            <h2>{{ 'title.steps'|trans({}, "messages") }}</h2>
            <ol>
                {% for step in recipe.recipeSteps %}
                    <li><p>{{ step.text|default('')|md2html }}</p><span class="details">{% if step.duration %}{{ step.duration }} {{ 'static.durations.minutes'|trans }}{% endif %}</span></li>
                {% endfor %}
            </ol>
        </div>

        {% if recipe.recipeHints|length > 0 %}
            <p class="spacer-medium">&nbsp;</p>
            <div class="hints">
                <h2>{{ 'title.hints'|trans({}, "messages") }}</h2>
                {% for hint in recipe.recipeHints %}
                    <div class="panel panel-default">
                        <div class="panel-body">{{ hint.text|default('')|md2html }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if recipe.recipeAlternatives|length > 0 %}
            <p class="spacer-medium">&nbsp;</p>
            <div class="alternatives">
                <h2>{{ 'title.recipeAlternatives'|trans({}, "messages") }}</h2>
                {% for alternative in recipe.recipeAlternatives %}
                    <div class="panel panel-default">
                        <div class="panel-body">{{ alternative.text|default('')|md2html }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if recipe.recipeLinks|length > 0 %}
            <p class="spacer-medium">&nbsp;</p>
            <div class="links">
                <h2>{{ 'title.links'|trans({}, "messages") }}</h2>
                <ul>
                {% for link in recipe.recipeLinks %}
                    <li>
                        <a href="{{ link.url }}">{{ link.linkText }}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endif %}

</div>

templates/front/recipes/_recipe_quicksearch.html.twig
<article class="recipe_list_quicksearch">
    <div class="row">
        {% set hasImage = recipe.images|length > 0 %}
        <div class="{{ hasImage ? 'col-md-8' : 'col-md-12' }}">
            <h4>
                <a href="{{ path('recipes_show', {slug: recipe.slug}) }}">
                    {{ recipe.title }}
                </a>
            </h4>

            <p class="recipe-metadata">
                {% if recipe.ratingGlobal %}
                    <span class="metadata">{{ recipe.ratingGlobal|rating(5, "fa-norm", true) }} ({{ recipe.ratingGlobal }})</span>
                {% endif %}
                {{ include('front/recipes/_recipe_tags.html.twig') }}
                <span class="metadata"><a href="{{ path('user_profile', {'username': recipe.author.username}) }}"><i class="fa fa-user"></i> {{ recipe.author.fullName }}</a></span>

            </p>

            {{ recipe.summary|default('')|md2html }}

            <br>
            {% if app.user and app.user.activeRecipeList and not app.user.activeRecipeList.getRecipes.contains(recipe) %}
                <a class="btn btn-success btn-sm"
                   target="_blank"
                   href="{{ path('recipelists_add_to_active', {'id': recipe.id}) }}">
                    {{ 'action.add_to_activ_recipelist'|trans }}
                </a>
            {% endif %}
        </div>
        {% if hasImage %}
        <div class="col-md-4">
            <img class="smallimage" src="{{ vich_uploader_asset(recipe.images[0], 'imageFile') }}">
        </div>
        {% endif %}
    </div>
</article>

templates/front/recipes/_recipe_tags.html.twig
{% if not recipe.recipeTags.empty %}
    <span class="recipe-recipeTags">
        {% for tag in recipe.recipeTags %}
            <span class="label label-default">
                <i class="fa fa-tag"></i> {{ tag.name }}
            </span>
        {% endfor %}
    </span>
{% endif %}

templates/front/recipes/comment_form_error.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'comment_form_error' %}

{% block main %}
    <h1 class="text-danger">{{ 'title.comment_error'|trans }}</h1>

    <div class="well">
        {{ include('front/recipes/_comment_form.html.twig') }}
    </div>
{% endblock %}

templates/front/recipes/filter.html.twig
{% extends 'front/layout.html.twig' %}

{% block body_id 'recipes_filter' %}

{% block main %}
    <h1>{{ 'title.filter_recipes'|trans }}</h1>
    {{ form_start(form) }}
    {{ form_row(form.text) }}
    {{ form_row(form.authorRecipeLists, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': recipeLists|join('|')}}) }}
    {{ form_row(form.recipeTags, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': recipeTags|join('|')}}) }}
    {{ form_row(form.ingredients, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': form.ingredients.vars.ingredients|join('|')}}) }}
    {{ form_row(form.ingredients_exclude, {'attr' : {'class': 'stXtokenField', 'data-availabeTokens': form.ingredients_exclude.vars.ingredients|join('|')}}) }}
    {{ form_row(form.recipeRating) }}
    {{ form_row(form.private) }}
    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.filter) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.random, {'attr': {'class': ' pull-right-lg'}}) }}
        </div>
    </div>
    {{ form_end(form) }}
    <p class="spacer-medium">&nbsp;</p>

    {% if recipes %}
        {% for recipe in recipes %}

            {{ include('front/recipes/_recipe_rowdisplay.html.twig', {recipe: recipe})|raw }}
        {% else %}
            <div class="well">{{ 'messages.no_recipes_found'|trans }}</div>
        {% endfor %}

        {% if recipes.haveToPaginate|default(false) %}
            <div class="navigation text-center">
                {{ pagerfanta(recipes, 'twitter_bootstrap3_translated', {routeName: 'recipes_filter_paginated'}) }}
            </div>
        {% endif %}
    {% endif %}

    {% if recultRecipe %}
        {{ include('front/recipes/_recipe.html.twig', {recipe: recultRecipe}) }}
    {% endif %}
{% endblock %}

{% block sidebar %}
    {{ parent() }}
    {{ include('front/recipes/_rss.html.twig') }}
{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script>
        require("assets{{ asset('js/pages/recipes/filter.js') }}");
    </script>
{% endblock %}